language: cpp

compiler: gcc
env:
  global:
    - COMPILER=g++-4.9

sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - valgrind
      - owfs
      - mosquitto
    
before_install:
  - pushd ..
  - git clone https://github.com/eclipse/paho.mqtt.c.git
  - cd paho.mqtt.c
  - mkdir build && cd build
  - cmake -DPAHO_WITH_SSL=TRUE -DPAHO_BUILD_DOCUMENTATION=FALSE -DPAHO_BUILD_SAMPLES=FALSE -DPAHO_ENABLE_TESTING=FALSE ..
  - make && sudo make install
  - cd ../..
  - git clone https://github.com/eclipse/paho.mqtt.cpp.git
  - cd paho.mqtt.cpp
  - mkdir build && cd build
  - cmake -DPAHO_WITH_SSL=TRUE -DPAHO_MQTT_C_PATH=../../paho.mqtt.c ..
  - make && sudo make install
  - sudo ldconfig
  - popd

install:
  - sudo pip install -U "cpp-coveralls"
  - sudo /etc/init.d/owhttpd stop
  - sudo /etc/init.d/owftpd stop
  - sudo /etc/init.d/owserver stop
  - sudo cp /home/travis/build/FragJage/MqttOwfs/owfs.conf /etc/owfs.conf
  - sudo /etc/init.d/owserver start

script:
  - cmake . -G"Unix Makefiles" -DCMAKE_CXX_COMPILER=$(which $COMPILER)
  - make
  - coveralls --include src --gcov-options '\-lp' --gcov 'gcov-4.9'

after_success:
  - ./test/bin/unittest
  - valgrind --error-exitcode=0 --leak-check=full ./test/bin/unittest

